services:
  paraphraser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paraphraser
    expose:
      - 65535:65535
    networks:
      - careerspeak
    volumes:
      - ../~:/home/python/paraphraser/~

networks:
  careerspeak:
    external: true
